### ISSUE TITLE
QR Code Menu Issue - Map Guide Code

### ISSUE THREAD

**Issue by nilesdorn** [davidrumseymapcenter/qr-code-menu#2]
The mapguide.png QR code link is broken. It links to qr.io which is the service we don't have a plan for, instead of the libguide. All the other QR codes in the QR Code Menu work. I've used the following website in the past to create permanent QR codes: [https://www.qr-code-generator.com/](https://www.qr-code-generator.com/)

As far as I know this website doesn't provide a way to manage created QR codes, so it may be better for one-use QR codes, like those used for events we host.

**Comment by ect123** [comment]
Thanks @nilesdorn. I'm going to use bit.ly for now for all new QR codes we create as they don't expire and we can track number of scans.

**Comment by ect123** [comment]
fixed with #1
